### ISSUE TITLE
Don't pin dependency version in requirments.txt

### ISSUE THREAD

**Issue by ujjwal96** [pytorn/hackr#15]
From https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires 
> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

So requirements can look like:
```
Faker>=0.8.4, <0.9
requests>=2.18.4, <2.19
```

It's just a best practice and not a necessity so feel free to close the issue if you don't see problem with current file 👍

**Comment by ashwini0529** [comment]
Hey @ujjwal96 , Thank you for bringing this to notice. I'll change it. 👍
