### ISSUE TITLE
Image Encoding

### ISSUE THREAD

**Issue by akshitgrover** [pytorn/hackr#16]
Handling images is a tedious task but a common one. Maybe we can create functionality to encode and decode images to base64.

**Comment by shubhodeep9** [comment]
@akshitgrover that's a wonderful idea, do you have any ideas to proceed with?

**Comment by akshitgrover** [comment]
An image can be read as binary and then encoded using base64.

**Comment by akshitgrover** [comment]
Can i work on this ?

**Comment by shubhodeep9** [comment]
Hi @akshitgrover , I checked PR #17 and it seems fine. But before I review it, why don't you write some tests for it, so that it becomes easier for me to review and merge it.
I see that someone else created the PR, so fork that and create tests for it, or modifications you find suitable.

**Comment by akshitgrover** [comment]
They are using separate files for storing each image, why not create a JSON file to store.
I will work on this.

**Comment by shubhodeep9** [comment]
@akshitgrover Ok, create a fork from this parent repo, and work on it. We will compare the different use cases.

**Comment by akshitgrover** [comment]
Should I write tests for #17  or the modified JSON implementation of #17 ?

**Comment by shubhodeep9** [comment]
@akshitgrover I'd suggest implement the JSON, if you think it is better.

**Comment by akshitgrover** [comment]
On it.

**Comment by akshitgrover** [comment]
I implemented JSON should I create a PR.
P.S. Tests are still left, Will create then soon.

**Comment by shubhodeep9** [comment]
@akshitgrover yes, create a PR, I will review it.
You go on with the tests ASAP.

**Comment by akshitgrover** [comment]
I will finish the tests soon, I am using matplotlib to view the decoded images.
P.S. I created a PR

**Comment by akshitgrover** [comment]
#20
