### ISSUE TITLE
Readthedocs build fails

### ISSUE THREAD

**Issue by ashwini0529** [pytorn/hackr#31]
Although it generates a documentation at http://hackr.readthedocs.io/en/latest/

Readthedocs build fails.

Complete log: https://readthedocs.org/projects/hackr/builds/6087206/

Integrating readthedocs like http://coala.readthedocs.io/en/latest/  would be amazing.

**Comment by PseudoAj** [comment]
The root cause of the issue is:
> This is caused by an empty toctree

Original thread here: [https://github.com/rtfd/readthedocs.org/issues/2398](https://github.com/rtfd/readthedocs.org/issues/2398)

**Comment by PseudoAj** [comment]
Greate PR here: https://github.com/pytorn/hackr/pull/32. Please kindly test it out
