### ISSUE TITLE
[Suggestion]Develop APIs

### ISSUE THREAD

**Issue by ashwini0529** [pytorn/hackr#40]
How about extending it to create APIs(web)? 
Just a random thought. 😄 
cc @shubhodeep9 @invinciblycool

**Comment by westminsterabi** [comment]
So by that do you mean that there should be an API somewhere on the web where you can access all of the functionality of the library?

**Comment by ashwini0529** [comment]
No no. Something that enables user to create APIs like what Flask etc does.

**Comment by ba11b0y** [comment]
Considering hackathons, a basic API generator function would be great, which can take parameters including the endpoint URL, the request method, and the content to be served/accepted.
We could use DRF for that, but will it be feasible, if yes, I would love to work on this.

**Comment by samuelrey** [comment]
Who is working on this?

**Comment by ba11b0y** [comment]
https://github.com/squeaky-pl/japronto can also be a great option.
Thoughts.

**Comment by ashwini0529** [comment]
As of now, we've a complete different project for handling web apis. 
Please have a look at https://github.com/pytorn/torn 😄
