### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by ashwini0529** [pytorn/hackr#5]
No tests have been written as of now. Writing tests would be very helpful.

**Comment by Emanon42** [comment]
Looks fun! But how can I write unit test for random generator (forgive my innocence, I am new to python)?

**Comment by ashwini0529** [comment]
There're other functions as well. Please have a look at other modules as well.  :)

**Comment by theycallmemac** [comment]
Do you specifically want tests for each feature offered as described in the README.md file? If so, I'll take this on.

**Comment by ashwini0529** [comment]
Yes, that would be great. All the functions present in the library.

**Comment by theycallmemac** [comment]
No problem, you can assign this to me so.

**Comment by ashwini0529** [comment]
Sure thing! 👍

**Comment by edo-vi** [comment]
if it's not a problem I started writing some tests, I didn't see @theycallmemac post here

**Comment by ashwini0529** [comment]
@theycallmemac are you still working on this issue?

**Comment by theycallmemac** [comment]
I am, but I'll let @edo-vi work away, if they aren't sufficient, let me know and I'll see what I can do! best of luck

**Comment by ashwini0529** [comment]
@theycallmemac meanwhile you can check https://github.com/pytorn/hackr/issues/8 😄

**Comment by samuelrey** [comment]
It may be worth considering to specify which function you'll test as well as the cases they cover. That way multiple contributors could work on tests & the pull request will be one, cohesive iteration.

**Comment by samuelrey** [comment]
I noticed that between https://github.com/pytorn/hackr/pull/14 and https://github.com/pytorn/hackr/pull/33 that the tests live in different places. Was this intentional? Could we move them to the same place?

**Comment by samuelrey** [comment]
I am testing ipv4 & ipv6!

**Comment by ashwini0529** [comment]
@samuelrey That was unintentional.
Can you please put all the tests to a single path? Also, tests need to be uniform.

**Comment by samuelrey** [comment]
Gotcha!

**Comment by samuelrey** [comment]
What version of python should we be targeting?

**Comment by ashwini0529** [comment]
Upto 3

**Comment by theycallmemac** [comment]
Has anything been done on this?

**Comment by samuelrey** [comment]
I lost my local changes D:
Will update you on Saturday!

**Comment by shubhodeep9** [comment]
Closing this issue,
Any discussions regarding tests, let's move it to #51
