### ISSUE TITLE
Implement cryptography functions

### ISSUE THREAD

**Issue by ashwini0529** [pytorn/hackr#52]
Many times, you need your data to be encrypted. One possible aspect could be implementing blockchain in your hackathon project.
It would be great if we could implement encryption related functionalities in the library.

Few things that could be taken care of
- encryption (bcrypt, md5, hashing algorithms)
- decryption

**Comment by TwoRice** [comment]
I could have a look at doing this, I'm not available right now, so I'd have to pick it up in a day or two. Are you just looking for a file to wrap up some common hashing, and encryption/decryption functions?

If someone wants to pick this up before me, feel free.

**Comment by rosdyana** [comment]
Hi, I add PR about add cryptography here #57 
cheers!
