### ISSUE TITLE
fetching crypto values

### ISSUE THREAD

**Issue by ashwini0529** [pytorn/hackr#58]
Maybe we could extend the support for getting crypto values?
Something like `hackr.crypto.convert('eth','usd')` would fetch the current eth to usd?

**Comment by alanfgn** [comment]
to be sure, you want to find the encryption that turns eth into usd?
like 
`hackr.crypto.convert('hackr','0cbb7cc60b77fe81355c3b116837a5e50b747311')`
`'sha1'`

**Comment by ashwini0529** [comment]
It could be a basic crypto currency conversion tool to return the values in some other currency.

Please check https://www.cryptocompare.com/
