### ISSUE TITLE
Plotting graphs and store it in a given path

### ISSUE THREAD

**Issue by ashwini0529** [pytorn/hackr#9]
To develop a function that allows to plot a graph providing the coordinates, and labels.

For example: 
```python
graph=hackr.plot.bar({"a":15,"b":10,"c":50}, xlabel=year, ylabel=issues)
graph.save('/path/to/save/')
```
The above code snippet would plot a graph with the provided coordinates and would save it in the mentioned path.

**Comment by cescobarf** [comment]
What kind of graphs do you have in mind? Is using a library like matplotlib ok?

**Comment by pprmint** [comment]
matplotlib should be enough for this I think. Probably just need to create a wrapper class for the actual calls.

**Comment by ashwini0529** [comment]
Matplotlib works. Can use different type of graphs that a user can choose.
For eg `hack.—.bar(—-)` or `hackr.—(type=bar)`

**Comment by luckyagarwal** [comment]
@ashwini0529 i want to work on this!

**Comment by ashwini0529** [comment]
Sure thing. 👍🎉

**Comment by 7Orion7** [comment]
Is it ok if I also want to give his a try?

**Comment by ashwini0529** [comment]
Sure, go ahead! :tada:

**Comment by ashwini0529** [comment]
Hey @7Orion7  on it?

**Comment by Shubhamsharma09** [comment]
hey @ashwini0529, we have to add a new file for this function or not.

**Comment by Shubhamsharma09** [comment]
At least reply so I can do some other projects.

**Comment by ashwini0529** [comment]
Hey @Shubhamsharma09 really sorry for the late reply.

I think moving up with a new file that plots graphs. 😄

**Comment by Shubhamsharma09** [comment]
ok, working on it. :+1:

**Comment by 7Orion7** [comment]
Almost finished a first version. Will send a merge request tomorrow :)

**Comment by 7Orion7** [comment]
Almost finished a first version. Will send a merge request today :)

**Comment by ashwini0529** [comment]
@Shubhamsharma09 are you on it? I guess @7Orion7 has worked on it.

**Comment by Shubhamsharma09** [comment]
@ashwini0529 bro r u there?

**Comment by ashwini0529** [comment]
Hey @Shubhamsharma09 I think @7Orion7 has finished the first version. Can you please send a PR so that @7Orion7 doesn't repeat the same work again.?

**Comment by Shubhamsharma09** [comment]
okkk

**Comment by Shubhamsharma09** [comment]
@ashwini0529 r u there, anything regarding my PR.

**Comment by ashwini0529** [comment]
@shubhodeep9 Can you please look into @Shubhamsharma09 's PR? 😄

**Comment by shubhodeep9** [comment]
@ashwini0529 yes just give me sometime. @Shubhamsharma09 don't worry, I will look into ASAP

**Comment by Shubhamsharma09** [comment]
Thank a lot @shubhodeep9. :)
